// Code generated by "stringer -type=Algorithm -trimprefix=Algorithm reader.go"; DO NOT EDIT.

package hash

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlgorithmNone-0]
	_ = x[AlgorithmMD5-1]
	_ = x[AlgorithmCRC32-2]
	_ = x[AlgorithmCRC32C-3]
	_ = x[AlgorithmCRC64NVME-4]
	_ = x[AlgorithmSHA1-5]
	_ = x[AlgorithmSHA256-6]
}

const _Algorithm_name = "NoneMD5CRC32CRC32CCRC64NVMESHA1SHA256"

var _Algorithm_index = [...]uint8{0, 4, 7, 12, 18, 27, 31, 37}

func (i Algorithm) String() string {
	if i < 0 || i >= Algorithm(len(_Algorithm_index)-1) {
		return "Algorithm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Algorithm_name[_Algorithm_index[i]:_Algorithm_index[i+1]]
}
