/*
 * MinIO Cloud Storage, (C) 2017 MinIO, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package hash

import (
	"bytes"
	"encoding/hex"
	"errors"
	"hash"
	"io"

	"storj.io/minio/pkg/etag"
)

//go:generate stringer -type=Algorithm -trimprefix=Algorithm $GOFILE

var errNoEarlyChecksums = errors.New("checksums must not be requested until all data has been read")

// Algorithm represents a checksum algorithm.
type Algorithm int

const (
	AlgorithmNone Algorithm = iota
	AlgorithmMD5
	AlgorithmCRC32
	AlgorithmCRC32C
	AlgorithmCRC64NVME
	AlgorithmSHA1
	AlgorithmSHA256
)

// DigestLen returns the size of the message digest generated by the algorithm.
// If the algorithm is invalid, DigestLen returns -1.
func (algo Algorithm) DigestLen() int {
	switch algo {
	case AlgorithmNone:
		return 0
	case AlgorithmMD5:
		return 16
	case AlgorithmCRC32, AlgorithmCRC32C:
		return 4
	case AlgorithmCRC64NVME:
		return 8
	case AlgorithmSHA1:
		return 20
	case AlgorithmSHA256:
		return 32
	default:
		return -1
	}
}

// Reader computes the checksum of read bytes.
type Reader interface {
	io.Reader

	// Size returns the absolute number of bytes the Reader will return during reading.
	// It returns -1 for unlimited data.
	Size() int64

	// ActualSize returns the pre-modified size of the object.
	ActualSize() int64

	// Checksums returns the checksums of the content. It must not be called until
	// all data has been read (indicated by Read returning io.EOF).
	Checksums() (map[Algorithm][]byte, error)
}

// A defaultReader is a Reader that optionally computes
// the SHA256 checksum of the content.
//
// If the reference values for the ETag and content SHA26
// are not empty then it will check whether the computed
// match the reference values.
type defaultReader struct {
	src       io.Reader
	bytesRead int64
	eof       bool

	size       int64
	actualSize int64

	checksum      etag.ETag
	contentSHA256 []byte

	sha256 hash.Hash
}

// NewDefaultReader returns a new Reader that wraps src. The reader computes the
// MD5 checksum of everything it reads, and no other checksums will be returned
// when invoking the Reader's Checksums method.
//
// If size resp. actualSize is unknown at the time of calling
// NewDefaultReader then it should be set to -1.
//
// NewDefaultReader may try merge the given size, MD5 and SHA256 values
// into src - if src is a default reader - to avoid computing the same
// checksums multiple times.
func NewDefaultReader(src io.Reader, size int64, md5Hex, sha256Hex string, actualSize int64) (Reader, error) {
	MD5, err := hex.DecodeString(md5Hex)
	if err != nil {
		return nil, BadDigest{ // TODO(aead): Return an error that indicates that an invalid ETag has been specified
			ExpectedMD5:   md5Hex,
			CalculatedMD5: "",
		}
	}
	SHA256, err := hex.DecodeString(sha256Hex)
	if err != nil {
		return nil, SHA256Mismatch{ // TODO(aead): Return an error that indicates that an invalid Content-SHA256 has been specified
			ExpectedSHA256:   sha256Hex,
			CalculatedSHA256: "",
		}
	}

	// Merge the size, MD5 and SHA256 values if src is a Reader.
	// The size may be set to -1 by callers if unknown.
	if r, ok := src.(*defaultReader); ok {
		if r.bytesRead > 0 {
			return nil, errors.New("hash: already read from hash reader")
		}
		if len(r.checksum) != 0 && len(MD5) != 0 && !etag.Equal(r.checksum, etag.ETag(MD5)) {
			return nil, BadDigest{
				ExpectedMD5:   r.checksum.String(),
				CalculatedMD5: md5Hex,
			}
		}
		if len(r.contentSHA256) != 0 && len(SHA256) != 0 && !bytes.Equal(r.contentSHA256, SHA256) {
			return nil, SHA256Mismatch{
				ExpectedSHA256:   hex.EncodeToString(r.contentSHA256),
				CalculatedSHA256: sha256Hex,
			}
		}
		if r.size >= 0 && size >= 0 && r.size != size {
			return nil, ErrSizeMismatch{Want: r.size, Got: size}
		}

		r.checksum = etag.ETag(MD5)
		r.contentSHA256 = SHA256
		if r.size < 0 && size >= 0 {
			r.src = etag.Wrap(io.LimitReader(r.src, size), r.src)
			r.size = size
		}
		if r.actualSize <= 0 && actualSize >= 0 {
			r.actualSize = actualSize
		}
		return r, nil
	}

	var hash hash.Hash
	if size >= 0 {
		src = io.LimitReader(src, size)
	}
	if len(SHA256) != 0 {
		hash = newSHA256()
	}
	return &defaultReader{
		src:           etag.NewReader(src, etag.ETag(MD5)),
		size:          size,
		actualSize:    actualSize,
		checksum:      etag.ETag(MD5),
		contentSHA256: SHA256,
		sha256:        hash,
	}, nil
}

func (r *defaultReader) Read(p []byte) (int, error) {
	n, err := r.src.Read(p)
	r.bytesRead += int64(n)
	if r.sha256 != nil {
		r.sha256.Write(p[:n])
	}

	r.eof = errors.Is(err, io.EOF)

	if r.eof { // Verify content SHA256, if set.
		if r.sha256 != nil {
			if sum := r.sha256.Sum(nil); !bytes.Equal(r.contentSHA256, sum) {
				return n, SHA256Mismatch{
					ExpectedSHA256:   hex.EncodeToString(r.contentSHA256),
					CalculatedSHA256: hex.EncodeToString(sum),
				}
			}
		}
	} else if err != nil {
		if v, ok := err.(etag.VerifyError); ok {
			return n, BadDigest{
				ExpectedMD5:   v.Expected.String(),
				CalculatedMD5: v.Computed.String(),
			}
		}
	}
	return n, err
}

// Size returns the absolute number of bytes the Reader
// will return during reading. It returns -1 for unlimited
// data.
func (r *defaultReader) Size() int64 { return r.size }

// ActualSize returns the pre-modified size of the object.
// DecompressedSize - For compressed objects.
func (r *defaultReader) ActualSize() int64 { return r.actualSize }

// Checksums returns the checksums of the content. It must not be called until
// all data has been read (indicated by Read returning io.EOF).
func (r *defaultReader) Checksums() (map[Algorithm][]byte, error) {
	if !r.eof {
		return nil, errNoEarlyChecksums
	}
	if t, ok := r.src.(etag.Tagger); ok {
		return map[Algorithm][]byte{
			AlgorithmMD5: t.ETag(),
		}, nil
	}
	return nil, errors.New("source reader cannot provide MD5")
}
